### ISSUE TITLE
能否修改路由表呢

### ISSUE THREAD

**Issue by linKnowEasy** [xujialiang/iOSRoutingTable#1]
感谢您的分享
想请教一下是否能修改 iOS 的 路由表呢？ 试过调用 ioctl() 方法, 好像还是没有修改成功.
在不越狱的情况下, 有相关的思路推荐么
如能抽空看看, 不胜感激。

**Comment by xujialiang** [comment]
修改路由表 可以用network extension 实现。

**Comment by linKnowEasy** [comment]
感谢, 通过  network extension 指定 IP 变相实现了

**Comment by zhjangbolin** [comment]
> 感谢, 通过 network extension 指定 IP 变相实现了

大佬，能发个demo看看么

**Comment by linKnowEasy** [comment]
@zhjangbolin 
本质就是通过 network extension  开发 进行 IP 过滤转发
你可以搜一下 iOS   network extension 开发  的相关资料, 核心是 PacketTunnelProvider

**Comment by zhjangbolin** [comment]
> @zhjangbolin 本质就是通过 network extension 开发 进行 IP 过滤转发 你可以搜一下 iOS network extension 开发 的相关资料, 核心是 PacketTunnelProvider

好的，多谢大佬
